[package]
name = "pine-tree-tax"
version = "0.0.1"

[dependencies]
csv = "1.0.0-beta.5"
chrono = { version = "0.4", features = ["serde"] }
serde = "1"
serde_derive = "1"
clap = "2.29.0"
maplit = "1.0.1"
